### ISSUE TITLE
 Getting Google ads to show with the AdSense module

### ISSUE THREAD

**Issue by micoots** [GreenMeteor/humhub-adsense-module#1]
### What steps will reproduce the problem?

Install AdSense module from Browse online area

### What is the expected result?

AdSense works without a problem

### What do you get instead?

`Refused to load the script 'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js' because it violates the following Content Security Policy directive: "script-src 'self' 'nonce-_someverylongstring_' 'unsafe-inline' 'unsafe-eval' 'report-sample'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.1
| PHP version      |  7.4
| Operating system | CentOS 8

There's no error from HumHub, this error is seen using Chrome developer console (ctrl-shft-J).

Because of the CSP, google ads don't show up on the site.

I've spend 3 hours on this already reading up on CSP items and changing my rules in:

/home/somepath/protected/config/web,php

but to no avail.

I have to full CSP defined here:

[https://docs.humhub.org/docs/admin/security/#web-security-configuration](https://docs.humhub.org/docs/admin/security/#web-security-configuration)

With my script-src section showing:

                                        "script-src" => [
                                                "self" => true,
                                                "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",
                                                "unsafe-inline" => true,
                                                "unsafe-eval" => true,
                                                "report-sample" => true
                                        ],

I did also try an:

                                        "script-src" => [
                                                "self" => true,
                                                "allow" => [
                                                "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",
                                                ],
                                                "unsafe-inline" => true,
                                                "unsafe-eval" => false,
                                                "report-sample" => true
                                        ],

but both do the same thing.

Please assist it's tricky!

**Comment by micoots** [comment]
Hi,

I trouble-shooted further and the issue isn't with the script-src of the pagead2 etc.

Chrome shows the issue as:

`<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>`

So even though the "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" is allowed, the above is the one that is causing the error.

Please assist, I've searched the web and there's not much I could find about this.

**Comment by ArchBlood** [comment]
We'll look into this more, at this time we're still trying to update all of our modules, thanks to @humhub some of our modules have already been updated.

**Comment by ArchBlood** [comment]
Try replacing 
```php
<script> (adsbygoogle = window.adsbygoogle || []).push({}); </script>
```
to

```php
<script <?= \humhub\libs\Html;::nonce() ?>>(adsbygoogle = window.adsbygoogle || []).push({});</script>
```

**Comment by micoots** [comment]
Hi. Thank you for your response however I don't understand how this can be done?

I raised this issue based on CSP rules defined and what to put into the CSP rules to allow for them to not block Google Ads in the browser.

What CSP rule needs to be added to allow for this?

I don't know of any such thing to add a:

`<script <?= \humhub\libs\Html;::nonce() ?>>(adsbygoogle = window.adsbygoogle || []).push({});</script>`

in CSP?

Please explain.

**Comment by ArchBlood** [comment]
I would think the below should work. :thinking: 

```php
"script-src" => [
   "self" => true,
   "allow" => [
       'https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js/'
   ]
],
```
As for the the above snippet, on [line 22](https://github.com/GreenMeteor/humhub-adsense-module/blob/master/widgets/views/adframe.php#L22) replace this code with the provided and add the use class that was also provided.

**Comment by ArchBlood** [comment]
> Hi,
> 
> I trouble-shooted further and the issue isn't with the script-src of the pagead2 etc.
> 
> Chrome shows the issue as:
> 
> `<script> (adsbygoogle = window.adsbygoogle || []).push({}); </script>`
> 
> So even though the "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js" is allowed, the above is the one that is causing the error.

Looking into this error more, it seems that this error only pops up when your Google AdSense account hasn't been approved by Google yet or the site itself hasn't been reviewed and approved
