### ISSUE TITLE
head.php not rendering code

### ISSUE THREAD

**Issue by Schillers** [GreenMeteor/humhub-adsense-module#2]
#### Using Google AdSense.
The first step to use Google AdSense is to get the HumHub site verified by placing a string similar to "<script data-ad-client="ca-pub-xxxxxxxxxxxxxxxx" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>" into the \<head> of the site.

I have installed the HumHub Google AdSense module and signed up for an AdSense account. The information input into the AdSense module requires a "slot" input which is not made available in the first instance by Google AdSense, I have since retrieved this value but would still like to place the code into the \<head> of the site. To circumvent this, I have attempted to use Custom HTML and place the String into the \<head> of the site by using the "protected/humhub/views/layouts/head.php" as outlined in [Issue #2663](https://github.com/humhub/humhub/issues/2663) and [Issue #4802](https://github.com/humhub/humhub/issues/4802). After placing this string and waiting for all CRON and SQL jobs to run, clearing the cache and trying on multiple devices the string still does not exist in the \<head> of the site.

### What is the expected result?
After placing the string in the "protected/humhub/views/layouts/head.php" file, I would expect to see "<script data-ad-client="ca-pub-xxxxxxxxxxxxxxxx" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>" placed in the \<head> of the website as per Google AdSense Guidelines.

### What do you get instead?
The code was not present in the of the site.

### Additional info

Q | A
-- | --
HumHub version | 1.7.2
PHP version | 7.3.23
Operating system | Linux

**Comment by ArchBlood** [comment]
The code is rendered in the widget view not the `head.php`

See here
https://github.com/GreenMeteor/humhub-adsense-module/blob/27474e2c352f93917589ba71e15b4a82953b2387/widgets/views/adframe.php#L15-L34

In all honesty it should be rendered first from here but wasn't, the module skeleton here needs updated badly we just don't have the time for this right now
https://github.com/GreenMeteor/humhub-adsense-module/blob/27474e2c352f93917589ba71e15b4a82953b2387/widgets/AdFrame.php#L12-L15

**Comment by ArchBlood** [comment]
@Schillers can you please check #3 p/r to see if the changes work for you? At the moment we're working on other things that we see wrong with the module at this time that will be fixed as soon as we can
